export interface NPCAppearance {
  "Skin Set Name (Available: TacticalTrader, MerchantRobes, ArmoredGuard, WastelandScavenger, EliteOperator, PirateTrader, SurvivalExpert, ApocalypseSurvivor, ScientistResearcher, BanditLeader, ArcticWolf, BlackoutOperator, DesertOutlaw, DragonLord, RustmasTrader, CowboyTrader, NightStalker, SteampunkMerchant, VikingWarrior, AzulMerchant, ToxicMerchant, TribalHunter)": string;
  "Custom Items with Skins (overrides preset if specified)": Record<string, number>;
}
export interface LanguageSettings {
  "Default Language": string;
  "Allow Per-Player Language": boolean;
}

// Supported languages for translation
export interface SupportedLanguage {
  code: string;
  name: string;
  deeplCode: string;
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'af', name: 'Afrikaans', deeplCode: 'AF' },
  { code: 'ar', name: 'Arabic', deeplCode: 'AR' },
  { code: 'ca', name: 'Catalan', deeplCode: 'CA' },
  { code: 'cs', name: 'Czech', deeplCode: 'CS' },
  { code: 'da', name: 'Danish', deeplCode: 'DA' },
  { code: 'de', name: 'German', deeplCode: 'DE' },
  { code: 'el', name: 'Greek', deeplCode: 'EL' },
  { code: 'en', name: 'English', deeplCode: 'EN' },
  { code: 'es-ES', name: 'Spanish (Spain)', deeplCode: 'ES' },
  { code: 'fi', name: 'Finnish', deeplCode: 'FI' },
  { code: 'fr', name: 'French', deeplCode: 'FR' },
  { code: 'he', name: 'Hebrew', deeplCode: 'HE' },
  { code: 'hu', name: 'Hungarian', deeplCode: 'HU' },
  { code: 'it', name: 'Italian', deeplCode: 'IT' },
  { code: 'ja', name: 'Japanese', deeplCode: 'JA' },
  { code: 'ko', name: 'Korean', deeplCode: 'KO' },
  { code: 'nl', name: 'Dutch', deeplCode: 'NL' },
  { code: 'no', name: 'Norwegian', deeplCode: 'NB' },
  { code: 'pl', name: 'Polish', deeplCode: 'PL' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)', deeplCode: 'PT-BR' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)', deeplCode: 'PT-PT' },
  { code: 'ro', name: 'Romanian', deeplCode: 'RO' },
  { code: 'ru', name: 'Russian', deeplCode: 'RU' },
  { code: 'sr', name: 'Serbian', deeplCode: 'SR' },
  { code: 'sv-SE', name: 'Swedish', deeplCode: 'SV' },
  { code: 'tr', name: 'Turkish', deeplCode: 'TR' },
  { code: 'uk', name: 'Ukrainian', deeplCode: 'UK' },
  { code: 'vi', name: 'Vietnamese', deeplCode: 'VI' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', deeplCode: 'ZH-CN' },
  { code: 'zh-TW', name: 'Chinese (Traditional)', deeplCode: 'ZH-TW' }
];

// Base language file structure for NPCTrader
export interface NPCTraderLanguageFile {
  "Greeting": string;
  "GreetingWithStatus": string;
  "VipStatus": string;
  "OffersAvailable": string;
  "OnCooldownGreeting": string;
  "ShowTradesConfirmation": string;
  "AboutServices": string;
  "CooldownInfo": string;
  "StandardCooldown": string;
  "VipCooldown": string;
  "OpeningInterface": string;
  "Goodbye": string;
  "Response_ShowTrades": string;
  "Response_AboutServices": string;
  "Response_MaybeLater": string;
  "Response_Understand": string;
  "Response_OpenInterface": string;
  "Response_ServicesFirst": string;
  "Response_NeverMind": string;
  "Response_WhenCanTrade": string;
  "Response_ThanksInfo": string;
  "Response_SoundsGood": string;
  "Response_ComeBackLater": string;
  "Response_ThankYou": string;
  "Response_Goodbye": string;
}

// Default English language file content
export const DEFAULT_LANGUAGE_CONTENT: NPCTraderLanguageFile = {
  "Greeting": "Greetings, {0}! I'm {1}, your local trader.",
  "GreetingWithStatus": "Greetings, {0}{1}! I'm {2}, your local trader.",
  "VipStatus": " (VIP Member)",
  "OffersAvailable": "I have {0} trade offers available!",
  "OnCooldownGreeting": "I'm sorry, but you must wait {0} before trading again.",
  "ShowTradesConfirmation": "Excellent! Let me show you what I have available...",
  "AboutServices": "I offer various trade packages for survivors like yourself. Bring me the required materials, and I'll give you valuable items in return.\\nEach trade has a cooldown period to keep things fair for everyone.",
  "CooldownInfo": "You can trade again in {0}.\\nYou have a {1} cooldown period.",
  "StandardCooldown": "Standard",
  "VipCooldown": "VIP",
  "OpeningInterface": "Opening my trading interface for you...",
  "Goodbye": "Safe travels, friend! Come back anytime you need to trade.",
  "Response_ShowTrades": "Show me your trades",
  "Response_AboutServices": "Tell me about your services",
  "Response_MaybeLater": "Maybe later",
  "Response_Understand": "I understand, goodbye",
  "Response_OpenInterface": "Open Trading Interface",
  "Response_ServicesFirst": "Actually, tell me about your services first",
  "Response_NeverMind": "Never mind",
  "Response_WhenCanTrade": "When can I trade again?",
  "Response_ThanksInfo": "Thanks for the info",
  "Response_SoundsGood": "Sounds good, thanks",
  "Response_ComeBackLater": "I'll come back later",
  "Response_ThankYou": "Thank you",
  "Response_Goodbye": "Goodbye"
};

export interface NotificationTypes {
  "Trade Success Notifications": boolean;
  "Trade Error Notifications": boolean;
  "Cooldown Notifications": boolean;
  "Permission Error Notifications": boolean;
  "Configuration Change Notifications": boolean;
  "NPC Management Notifications": boolean;
  "Conversation Notifications": boolean;
  "General Info Notifications": boolean;
}

export interface NCPIntegration {
  "Enable NCP Integration": boolean;
  "Use Chat Fallback if NCP Unavailable": boolean;
  "Notification Types": NotificationTypes;
}

export interface UISettings {
  [key: string]: string;
}

export interface RequiredItem {
  "Item Shortname": string;
  "Amount": number;
  "Skin ID": number;
}

export interface Reward {
  "Type": number;
  "Value": string;
  "Amount": number;
  "Skin ID": number;
}

export interface TradeOffer {
  "Display Name": string;
  "Required Items": RequiredItem[];
  "Rewards": Reward[];
  "Icon": string;
  "Permission Required": string;
}

export interface NPCTraderConfig {
  "NPC Display Name": string;
  "NPC Appearance": NPCAppearance;
  "Default Cooldown (seconds)": number;
  "VIP Cooldown (seconds)": number;
  "Language Settings": LanguageSettings;
  "NCP Integration": NCPIntegration;
  "UI Settings": UISettings;
  "Trade Offers": TradeOffer[];
}

export const AVAILABLE_ICONS = [
  'add', 'af', 'air_tank0', 'air_tank1', 'air_tank2', 'air_tank3', 'air_tank4', 'air_tank5',
  'alert_edit', 'ammunition', 'ar', 'arrow_right', 'authorize', 'backpack', 'bite', 'bleeding',
  'blueprint', 'blueprint_underlay', 'blunt_0', 'boosts', 'boosts_bright', 'bp-lock', 'broadcast',
  'brush', 'bullet', 'ca', 'cable', 'cards', 'cargo_ship_body', 'cart', 'change_code', 'check',
  'chevron_down', 'chevron_right_0', 'chicken', 'chinook_map_blades', 'chinook_map_body',
  'circle_closed', 'circle_closed_toEdge', 'circle_closed_white', 'circle_closed_white_toEdge',
  'circle_gradient', 'circle_open', 'circle_open_thick', 'clan', 'clear', 'clear_list', 'close',
  'close_door', 'clothing', 'cold', 'community_servers', 'connection', 'construction', 'cooking',
  'crate', 'cs', 'cup_water', 'da', 'de', 'deauthorize', 'demolish', 'demolish_cancel',
  'demolish_immediate', 'descend', 'device_add', 'dir_left', 'dir_right', 'discord 1', 'discord',
  'download', 'drone', 'drop', 'drowning', 'eat', 'el', 'electric_0', 'elevator_call',
  'elevator_down', 'elevator_up', 'embrella', 'embrella_bright', 'en', 'en-PT', 'enter',
  'equip_hood', 'eraser', 'es-ES', 'examine', 'exit', 'explosion', 'explosion_sprite',
  'extinguish', 'facebook', 'facebook-box', 'facepunch', 'fall', 'Favourite_active',
  'Favourite_inactive', 'favourite_servers', 'ferry', 'fi', 'file', 'film-reel',
  'film-slate-clapper', 'fire', 'fog_4', 'folder', 'folder_up', 'food_cooked', 'food_raw',
  'fork_and_spoon', 'fr', 'freezing', 'freezing-white', 'friends_servers', 'fun', 'fun_alt',
  'gear', 'gem', 'gem2', 'gem3', 'gesture_rock-paper-scissors', 'gesture_rps_paper',
  'gesture_rps_rock', 'gesture_rps_scissors', 'gesture-beat-chest', 'gesture-clap',
  'gesture-cut-throat', 'gesture-double-middle-finger', 'gesture-eyes-on-you', 'gesture-finger-gun',
  'gesture-frame', 'gesture-friendly', 'gesture-hurry', 'gesture-knuckles-crack', 'gesture-loser',
  'gesture-middle-finger', 'gesture-no-no', 'gesture-ok', 'gesture-ok-2', 'gesture-point',
  'gesture-raise-the-roof', 'gesture-shrug', 'gesture-shush', 'gesture-shushing',
  'gesture-shushing-2', 'gesture-silly-dance-1-alternative', 'gesture-silly-dance-2',
  'gesture-thumbs-down', 'gesture-thumbs-up', 'gesture-victory', 'gesture-watchingyou',
  'gesture-wave', 'gesture-wind-up-middle', 'greyout', 'greyout_large', 'handlebar',
  'hand-looting', 'he', 'health', 'history_servers', 'home', 'home_bright', 'horse_ride',
  'horse_ride_2', 'hot', 'hu', 'hurry', 'icon_age', 'icon_clear', 'icon_firework',
  'icon_firework_disabled', 'icon_genetics', 'icon_ground', 'icon_light',
  'icon_map_traveling-vendor (2)', 'icon_map_traveling-vendor', 'icon_map_traveling-vendor_alt',
  'icon_overall', 'icon_pixel_camera', 'icon_stage', 'icon_temperature', 'icon_water-intake',
  'icon_water-saturation', 'icon_yield', 'icon-locked', 'icon-map', 'icon-patrol-helicopter',
  'icon-submarine', 'icon-unlocked', 'icon-water-1', 'icon-water-2', 'icon-water-3',
  'icon-water-4', 'icon-water-5', 'icon-water-6', 'icon-water-7', 'icon-water-8', 'ignite_0',
  'info', 'input', 'instagram-logo', 'inventory', 'isbroken', 'iscooking', 'isloading',
  'isonfire', 'it', 'ja', 'joystick', 'key', 'kick', 'knock_door', 'ko', 'lan_servers',
  'level_0', 'level_metal', 'level_stone', 'level_top', 'level_wood', 'lick', 'light',
  'light_campfire', 'lightbulb', 'lightbulb-white', 'link', 'link_break', 'loading',
  'loading_white', 'lock', 'loot', 'lungs', 'maparrow', 'map-tunnel', 'marker_a', 'marker_b',
  'marker_c', 'market', 'maximum', 'meat', 'medical', 'menu_dots', 'modded_servers', 'nextframe',
  'nl', 'no', 'no_sleep', 'no_spawn', 'noun_Download_1015668_0', 'occupied', 'open', 'open_door',
  'ore', 'output', 'oxygen', 'palette', 'peace', 'pet_assist', 'pet_combat', 'pet_destroy',
  'pet_follow', 'pet_guard', 'pet_idle', 'pet_move', 'pet_pvp', 'phone', 'pickup', 'picture',
  'pills', 'pl', 'player_assist', 'player_carry', 'player_loot', 'plug-off', 'plug-on',
  'poison', 'poof_0', 'portion', 'power', 'premium_background', 'premium_facepunch_icon',
  'press', 'prevframe', 'pt-BR', 'pt-PT', 'radiation', 'rain', 'reddit', 'refresh',
  'refresh_filled', 'remove_cuffs', 'remove_hood', 'resource', 'rf_on', 'ro', 'rocket',
  'rotate', 'ru', 'rust', 'safe zone_0', 'save', 'security_0', 'shadow', 'shrug', 'sign',
  'skull_0', 'slash', 'sleeping', 'sleepingbag', 'square', 'square_gradient', 'sr', 'stab',
  'stairs', 'star', 'steam', 'stopwatch', 'store', 'study', 'submarine0', 'submarine1',
  'submarine2', 'submarine3', 'submarine4', 'submarine5', 'subtract', 'sv-SE', 'swing',
  'target', 'terrain', 'throw_back', 'thumbsup', 'tools', 'tr', 'train', 'translate', 'traps',
  'tree-fire', 'triangle_0', 'triangle_white', 'tweeter_0', 'twitter 1', 'twitter', 'uk',
  'unload', 'unlock', 'upgrade', 'vi', 'victory', 'voice', 'vote_down', 'vote_up',
  'wall.doorway.door', 'wall.window.bars', 'warning', 'warning_2', 'waving', 'weapon', 'web',
  'wet', 'White', 'whoa', 'workshop', 'xp', 'yt_icon_rgb', 'zh-CN'
];

export const SKIN_SETS = [
  'TacticalTrader', 'MerchantRobes', 'ArmoredGuard', 'WastelandScavenger',
  'EliteOperator', 'PirateTrader', 'SurvivalExpert', 'ApocalypseSurvivor',
  'ScientistResearcher', 'BanditLeader', 'ArcticWolf', 'BlackoutOperator',
  'DesertOutlaw', 'DragonLord', 'RustmasTrader', 'CowboyTrader',
  'NightStalker', 'SteampunkMerchant', 'VikingWarrior', 'AzulMerchant',
  'ToxicMerchant', 'TribalHunter'
];

// Complete Rust Items List
export const RUST_ITEMS = [
  'abovegroundpool', 'ammo.grenadelauncher.buckshot', 'ammo.grenadelauncher.he', 'ammo.grenadelauncher.smoke',
  'ammo.handmade.shell', 'ammo.nailgun.nails', 'ammo.pistol', 'ammo.pistol.fire', 'ammo.pistol.hv',
  'ammo.rifle', 'ammo.rifle.explosive', 'ammo.rifle.hv', 'ammo.rifle.incendiary', 'ammo.rocket.basic',
  'ammo.rocket.fire', 'ammo.rocket.hv', 'ammo.rocket.sam', 'ammo.rocket.smoke', 'ammo.shotgun',
  'ammo.shotgun.fire', 'ammo.shotgun.slug', 'ammo.snowballgun', 'antiradpills', 'apple', 'apple.spoiled',
  'arcade.machine.chippy', 'arrow.bone', 'arrow.fire', 'arrow.hv', 'arrow.wooden', 'attire.banditguard',
  'attire.bunny.onesie', 'attire.bunnyears', 'attire.hide.boots', 'attire.hide.helterneck', 'attire.hide.pants',
  'attire.hide.poncho', 'attire.hide.skirt', 'attire.hide.vest', 'attire.nesthat', 'attire.reindeer.headband',
  'autoturret', 'axe.salvaged', 'bandage', 'barrelcostume', 'barricade.concrete', 'barricade.metal',
  'barricade.sandbags', 'barricade.stone', 'barricade.wood', 'barricade.wood.cover', 'barricade.woodwire',
  'battery.small', 'bbq', 'beachchair', 'beachparasol', 'beachtable', 'beachtowel', 'bearmeat',
  'bearmeat.burned', 'bearmeat.cooked', 'bed', 'black.berry', 'black.raspberries', 'bleach', 'blood',
  'blue.berry', 'blueberries', 'blueprintbase', 'bone.armor.suit', 'bone.club', 'bone.fragments',
  'boogieboard', 'boots.frog', 'botabag', 'bow.compound', 'bow.hunting', 'box.repair.bench',
  'box.wooden', 'box.wooden.large', 'bucket.helmet', 'bucket.water', 'building.planner',
  'burlap.gloves', 'burlap.gloves.new', 'burlap.headwrap', 'burlap.shirt', 'burlap.shoes',
  'burlap.trousers', 'cactusflesh', 'cakefiveyear', 'campfire', 'can.beans', 'can.beans.empty',
  'can.tuna', 'can.tuna.empty', 'candycane', 'candycaneclub', 'car.key', 'carburetor1', 'carburetor2',
  'carburetor3', 'cctv.camera', 'ceilinglight', 'chainsaw', 'chair', 'charcoal', 'chicken.burned',
  'chicken.cooked', 'chicken.raw', 'chicken.spoiled', 'chineselantern', 'chocholate', 'clatter.helmet',
  'clone.black.berry', 'clone.blue.berry', 'clone.corn', 'clone.green.berry', 'clone.hemp',
  'clone.potato', 'clone.pumpkin', 'clone.red.berry', 'clone.white.berry', 'clone.yellow.berry',
  'cloth', 'coal', 'coffeecan.helmet', 'coffin.storage', 'composter', 'computerstation', 'corn',
  'crankshaft1', 'crankshaft2', 'crankshaft3', 'cratecostume', 'crossbow', 'crude.oil', 'cupboard.tool',
  'cursedcauldron', 'deer.skull.mask', 'deermeat.burned', 'deermeat.cooked', 'deermeat.raw',
  'diesel_barrel', 'diving.fins', 'diving.mask', 'diving.tank', 'diving.wetsuit', 'door.closer',
  'door.double.hinged.metal', 'door.double.hinged.toptier', 'door.double.hinged.wood',
  'door.hinged.industrial.a', 'door.hinged.metal', 'door.hinged.toptier', 'door.hinged.wood',
  'door.key', 'dragondoorknocker', 'dropbox', 'drumkit', 'ducttape', 'easter.bronzeegg',
  'easter.goldegg', 'easter.paintedeggs', 'easter.silveregg', 'easterbasket', 'easterdoorwreath',
  'electric.andswitch', 'electric.audioalarm', 'electric.battery.rechargable.large',
  'electric.battery.rechargable.medium', 'electric.battery.rechargable.small', 'electric.blocker',
  'electric.button', 'electric.cabletunnel', 'electric.counter', 'electric.doorcontroller',
  'electric.flasherlight', 'electric.fuelgenerator.small', 'electric.generator.small',
  'electric.hbhfsensor', 'electric.heater', 'electric.igniter', 'electric.laserdetector',
  'electric.orswitch', 'electric.pressurepad', 'electric.random.switch', 'electric.rf.broadcaster',
  'electric.rf.receiver', 'electric.simplelight', 'electric.sirenlight', 'electric.solarpanel.large',
  'electric.splitter', 'electric.sprinkler', 'electric.switch', 'electric.teslacoil', 'electric.timer',
  'electric.xorswitch', 'electrical.branch', 'electrical.combiner', 'electrical.memorycell',
  'elevator', 'explosive.satchel', 'explosive.timed', 'explosives', 'fat.animal', 'fertilizer',
  'fireplace.stone', 'firework.boomer.blue', 'firework.boomer.champagne', 'firework.boomer.green',
  'firework.boomer.orange', 'firework.boomer.red', 'firework.boomer.violet', 'firework.romancandle.blue',
  'firework.romancandle.green', 'firework.romancandle.red', 'firework.romancandle.violet',
  'firework.volcano', 'firework.volcano.red', 'firework.volcano.violet', 'fish.cooked', 'fish.minnows',
  'fish.raw', 'fish.troutsmall', 'fishingrod.handmade', 'fishtrap.small', 'flamethrower',
  'flameturret', 'flare', 'flashlight.held', 'floor.grill', 'floor.ladder.hatch', 'floor.triangle.grill',
  'floor.triangle.ladder.hatch', 'fluid.combiner', 'fluid.splitter', 'fluid.switch', 'fogmachine',
  'fridge', 'fun.bass', 'fun.cowbell', 'fun.flute', 'fun.guitar', 'fun.jerrycanguitar',
  'fun.tambourine', 'fun.trumpet', 'fun.tuba', 'furnace', 'furnace.large', 'fuse',
  'gates.external.high.stone', 'gates.external.high.wood', 'gears', 'geiger.counter',
  'generator.wind.scrap', 'ghostsheet', 'giantcandycanedecor', 'giantlollipops', 'gloweyes',
  'glue', 'granolabar', 'gravestone', 'green.berry', 'grenade.beancan', 'grenade.f1',
  'grenade.smoke', 'gun.water', 'gunpowder', 'guntrap', 'habrepair', 'halloween.candy',
  'halloween.lootbag.large', 'halloween.lootbag.medium', 'halloween.lootbag.small',
  'halloween.mummysuit', 'halloween.surgeonsuit', 'hammer', 'hammer.salvaged', 'hat.beenie',
  'hat.boonie', 'hat.candle', 'hat.cap', 'hat.dragonmask', 'hat.miner', 'hat.ratmask',
  'hat.wolf', 'hatchet', 'hazmatsuit', 'hazmatsuit.spacesuit', 'hazmatsuit_scientist',
  'hazmatsuit_scientist_peacekeeper', 'healingtea', 'healingtea.advanced', 'healingtea.pure',
  'heavy.plate.helmet', 'heavy.plate.jacket', 'heavy.plate.pants', 'hitchtroughcombo',
  'hobobarrel', 'hoodie', 'horse.armor.roadsign', 'horse.armor.wood', 'horse.saddle',
  'horse.saddlebag', 'horse.shoes.advanced', 'horse.shoes.basic', 'horsedung', 'horsemeat.burned',
  'horsemeat.cooked', 'horsemeat.raw', 'hosetool', 'hq.metal.ore', 'humanmeat.burned',
  'humanmeat.cooked', 'humanmeat.raw', 'humanmeat.spoiled', 'icepick.salvaged', 'innertube',
  'innertube.horse', 'innertube.unicorn', 'jacket', 'jacket.snow', 'jackhammer',
  'jackolantern.angry', 'jackolantern.happy', 'jar.pickle', 'kayak', 'keycard_blue',
  'keycard_green', 'keycard_red', 'knife.bone', 'knife.butcher', 'knife.combat',
  'ladder.wooden.wall', 'lantern', 'largecandles', 'largemedkit', 'leather', 'lmg.m249',
  'lock.code', 'lock.key', 'locker', 'longsword', 'lowgradefuel', 'lunar.firecrackers',
  'mace', 'machete', 'mailbox', 'map', 'mask.balaclava', 'mask.bandana', 'maxhealthtea',
  'maxhealthtea.advanced', 'maxhealthtea.pure', 'meat.boar', 'meat.pork.burned', 'meat.pork.cooked',
  'metal.facemask', 'metal.fragments', 'metal.ore', 'metal.plate.torso', 'metal.refined',
  'metalblade', 'metalpipe', 'metalspring', 'minihelicopter.repair', 'mining.pumpjack',
  'mining.quarry', 'mixingtable', 'modularcarlift', 'movembermoustache', 'movembermoustachecard',
  'multiplegrenadelauncher', 'mushroom', 'newyeargong', 'nightvisiongoggles', 'note',
  'oretea', 'oretea.advanced', 'oretea.pure', 'paddle', 'paddlingpool', 'pants', 'pants.shorts',
  'paper', 'partyhat', 'photo', 'photoframe.landscape', 'photoframe.large', 'photoframe.portrait',
  'piano', 'pickaxe', 'pistol.eoka', 'pistol.m92', 'pistol.nailgun', 'pistol.python',
  'pistol.revolver', 'pistol.semiauto', 'pistol.water', 'piston1', 'piston2', 'piston3',
  'pitchfork', 'planter.large', 'planter.small', 'plantfiber', 'pookie.bear', 'potato',
  'powered.water.purifier', 'propanetank', 'pumpkin', 'pumpkinbasket', 'radiationremovetea',
  'radiationremovetea.advanced', 'radiationremovetea.pure', 'radiationresisttea',
  'radiationresisttea.advanced', 'radiationresisttea.pure', 'red.berry', 'research.table',
  'researchpaper', 'rf.detonator', 'rf_pager', 'rifle.ak', 'rifle.bolt', 'rifle.l96',
  'rifle.lr300', 'rifle.m39', 'rifle.semiauto', 'riflebody', 'riot.helmet', 'roadsign.gloves',
  'roadsign.jacket', 'roadsign.kilt', 'roadsigns', 'rock', 'rocket.launcher', 'rope',
  'rug', 'rug.bear', 'rustige_egg_a', 'rustige_egg_b', 'rustige_egg_c', 'rustige_egg_d',
  'salvaged.cleaver', 'salvaged.sword', 'samsite', 'santabeard', 'santahat', 'scarecrow',
  'scarecrow.suit', 'scarecrowhead', 'scientistsuit_heavy', 'scrap', 'scraptea', 'scraptea.advanced',
  'scraptea.pure', 'scraptransportheli.repair', 'searchlight', 'secretlabchair', 'seed.black.berry',
  'seed.blue.berry', 'seed.corn', 'seed.green.berry', 'seed.hemp', 'seed.potato', 'seed.pumpkin',
  'seed.red.berry', 'seed.white.berry', 'seed.yellow.berry', 'semibody', 'sewingkit',
  'sheetmetal', 'shelves', 'shirt.collared', 'shirt.tanktop', 'shoes.boots', 'shotgun.double',
  'shotgun.pump', 'shotgun.spas12', 'shotgun.waterpipe', 'shutter.metal.embrasure.a',
  'shutter.metal.embrasure.b', 'shutter.wood.a', 'sickle', 'sign.hanging', 'sign.hanging.banner.large',
  'sign.hanging.ornate', 'sign.neon.125x125', 'sign.neon.125x215', 'sign.neon.125x215.animated',
  'sign.neon.xl', 'sign.neon.xl.animated', 'sign.pictureframe.landscape', 'sign.pictureframe.portrait',
  'sign.pictureframe.tall', 'sign.pictureframe.xl', 'sign.pictureframe.xxl', 'sign.pole.banner.large',
  'sign.post.double', 'sign.post.single', 'sign.post.town', 'sign.post.town.roof',
  'sign.wooden.huge', 'sign.wooden.large', 'sign.wooden.medium', 'sign.wooden.small',
  'skull.human', 'skull.trophy', 'skull.trophy.jar', 'skull.trophy.jar2', 'skull.trophy.table',
  'skull.wolf', 'skull_fire_pit', 'skulldoorknocker', 'skullspikes', 'skullspikes.candles',
  'skullspikes.pumpkin', 'sled', 'sled.xmas', 'sleepingbag', 'small.oil.refinery',
  'smallcandles', 'smallwaterbottle', 'smart.alarm', 'smart.switch', 'smg.2', 'smg.mp5',
  'smg.thompson', 'smgbody', 'snowball', 'snowballgun', 'snowmachine', 'snowman', 'sofa',
  'sparkplug1', 'sparkplug2', 'sparkplug3', 'spear.stone', 'spear.wooden', 'spiderweb',
  'spikes.floor', 'spinner.wheel', 'spookyspeaker', 'stash.small', 'sticks', 'stocking.large',
  'stocking.small', 'stone.pickaxe', 'stonehatchet', 'stones', 'storage.monitor', 'strobelight',
  'sulfur', 'sulfur.ore', 'sunglasses', 'sunglasses02black', 'sunglasses02camo', 'sunglasses02red',
  'sunglasses03black', 'sunglasses03chrome', 'sunglasses03gold', 'supply.signal', 'surveycharge',
  'syringe.medical', 'table', 'tactical.gloves', 'target.reactive', 'targeting.computer',
  'tarp', 'techparts', 'telephone', 'tool.binoculars', 'tool.camera', 'tool.instant_camera',
  'toolgun', 'torch', 'trap.bear', 'trap.landmine', 'tshirt', 'tshirt.long', 'tunalight',
  'twitch.headset', 'twitchsunglasses', 'valve1', 'valve2', 'valve3', 'vehicle.1mod.cockpit',
  'vehicle.1mod.cockpit.armored', 'vehicle.1mod.cockpit.with.engine', 'vehicle.1mod.engine',
  'vehicle.1mod.flatbed', 'vehicle.1mod.passengers.armored', 'vehicle.1mod.rear.seats',
  'vehicle.1mod.storage', 'vehicle.1mod.taxi', 'vehicle.2mod.flatbed', 'vehicle.2mod.fuel.tank',
  'vehicle.2mod.passengers', 'vehicle.chassis', 'vehicle.chassis.2mod', 'vehicle.chassis.3mod',
  'vehicle.chassis.4mod', 'vehicle.module', 'vending.machine', 'wall.external.high',
  'wall.external.high.ice', 'wall.external.high.stone', 'wall.frame.cell', 'wall.frame.cell.gate',
  'wall.frame.fence', 'wall.frame.fence.gate', 'wall.frame.garagedoor', 'wall.frame.netting',
  'wall.frame.shopfront', 'wall.frame.shopfront.metal', 'wall.graveyard.fence', 'wall.ice.wall',
  'wall.window.bars.metal', 'wall.window.bars.toptier', 'wall.window.bars.wood',
  'wall.window.glass.reinforced', 'watchtower.wood', 'water', 'water.barrel', 'water.catcher.large',
  'water.catcher.small', 'water.purifier', 'water.salt', 'waterjug', 'waterpump',
  'weapon.mod.8x.scope', 'weapon.mod.flashlight', 'weapon.mod.holosight', 'weapon.mod.lasersight',
  'weapon.mod.muzzleboost', 'weapon.mod.muzzlebrake', 'weapon.mod.silencer', 'weapon.mod.simplesight',
  'weapon.mod.small.scope', 'white.berry', 'wiretool', 'wolfmeat.burned', 'wolfmeat.cooked',
  'wolfmeat.raw', 'wolfmeat.spoiled', 'wood', 'wood.armor.helmet', 'wood.armor.jacket',
  'wood.armor.pants', 'woodcross', 'woodtea', 'woodtea.advanced', 'woodtea.pure', 'workbench1',
  'workbench2', 'workbench3', 'wrappedgift', 'wrappingpaper', 'xmas.decoration.baubels',
  'xmas.decoration.candycanes', 'xmas.decoration.gingerbreadmen', 'xmas.decoration.lights',
  'xmas.decoration.pinecone', 'xmas.decoration.star', 'xmas.decoration.tinsel', 'xmas.door.garland',
  'xmas.lightstring', 'xmas.lightstring.advanced', 'xmas.present.large', 'xmas.present.medium',
  'xmas.present.small', 'xmas.tree', 'xmas.window.garland', 'xmasdoorwreath', 'xylophone',
  'yellow.berry'
];

// Item display names mapping
export const ITEM_DISPLAY_NAMES: Record<string, string> = {
  'abovegroundpool': 'Above Ground Pool',
  'ammo.grenadelauncher.buckshot': '40mm Shotgun Round',
  'ammo.grenadelauncher.he': '40mm HE Grenade',
  'ammo.grenadelauncher.smoke': '40mm Smoke Grenade',
  'ammo.handmade.shell': 'Handmade Shell',
  'ammo.nailgun.nails': 'Nailgun Nails',
  'ammo.pistol': 'Pistol Bullet',
  'ammo.pistol.fire': 'Incendiary Pistol Bullet',
  'ammo.pistol.hv': 'HV Pistol Ammo',
  'ammo.rifle': '5.56 Rifle Ammo',
  'ammo.rifle.explosive': 'Explosive 5.56 Rifle Ammo',
  'ammo.rifle.hv': 'HV 5.56 Rifle Ammo',
  'ammo.rifle.incendiary': 'Incendiary 5.56 Rifle Ammo',
  'ammo.rocket.basic': 'Rocket',
  'ammo.rocket.fire': 'Incendiary Rocket',
  'ammo.rocket.hv': 'High Velocity Rocket',
  'ammo.rocket.sam': 'SAM Ammo',
  'ammo.rocket.smoke': 'Smoke Rocket',
  'ammo.shotgun': '12 Gauge Buckshot',
  'ammo.shotgun.fire': '12 Gauge Incendiary Shell',
  'ammo.shotgun.slug': '12 Gauge Slug',
  'antiradpills': 'Anti-Radiation Pills',
  'apple': 'Apple',
  'apple.spoiled': 'Rotten Apple',
  'arcade.machine.chippy': 'Chippy Arcade Game',
  'arrow.bone': 'Bone Arrow',
  'arrow.fire': 'Fire Arrow',
  'arrow.hv': 'High Velocity Arrow',
  'arrow.wooden': 'Wooden Arrow',
  'attire.banditguard': 'Bandit Guard Gear',
  'attire.bunny.onesie': 'Bunny Onesie',
  'attire.bunnyears': 'Bunny Ears',
  'attire.hide.boots': 'Hide Boots',
  'attire.hide.helterneck': 'Hide Halterneck',
  'attire.hide.pants': 'Hide Pants',
  'attire.hide.poncho': 'Hide Poncho',
  'attire.hide.skirt': 'Hide Skirt',
  'attire.hide.vest': 'Hide Vest',
  'attire.nesthat': 'Nest Hat',
  'attire.reindeer.headband': 'Reindeer Antlers',
  'autoturret': 'Auto Turret',
  'axe.salvaged': 'Salvaged Axe',
  'bandage': 'Bandage',
  'barrelcostume': 'A Barrel Costume',
  'barricade.concrete': 'Concrete Barricade',
  'barricade.metal': 'Metal Barricade',
  'barricade.sandbags': 'Sandbag Barricade',
  'barricade.stone': 'Stone Barricade',
  'barricade.wood': 'Wooden Barricade',
  'barricade.wood.cover': 'Wooden Barricade Cover',
  'barricade.woodwire': 'Barbed Wooden Barricade',
  'battery.small': 'Battery - Small',
  'bbq': 'Barbeque',
  'beachchair': 'Beach Chair',
  'beachparasol': 'Beach Parasol',
  'beachtable': 'Beach Table',
  'beachtowel': 'Beach Towel',
  'bearmeat': 'Raw Bear Meat',
  'bearmeat.burned': 'Burnt Bear Meat',
  'bearmeat.cooked': 'Cooked Bear Meat',
  'bed': 'Bed',
  'black.berry': 'Black Berry',
  'black.raspberries': 'Black Raspberries',
  'bleach': 'Bleach',
  'blood': 'Blood',
  'blue.berry': 'Blue Berry',
  'blueberries': 'Blueberries',
  'blueprintbase': 'Blueprint',
  'bone.armor.suit': 'Bone Armor',
  'bone.club': 'Bone Club',
  'bone.fragments': 'Bone Fragments',
  'boogieboard': 'Boogie Board',
  'boots.frog': 'Frog Boots',
  'botabag': 'Bota Bag',
  'bow.compound': 'Compound Bow',
  'bow.hunting': 'Hunting Bow',
  'box.repair.bench': 'Repair Bench',
  'box.wooden': 'Wood Storage Box',
  'box.wooden.large': 'Large Wood Box',
  'bucket.helmet': 'Bucket Helmet',
  'bucket.water': 'Water Bucket',
  'building.planner': 'Building Plan',
  'burlap.gloves': 'Leather Gloves',
  'burlap.gloves.new': 'Burlap Gloves',
  'burlap.headwrap': 'Burlap Headwrap',
  'burlap.shirt': 'Burlap Shirt',
  'burlap.shoes': 'Burlap Shoes',
  'burlap.trousers': 'Burlap Trousers',
  'cactusflesh': 'Cactus Flesh',
  'cakefiveyear': 'Birthday Cake',
  'campfire': 'Camp Fire',
  'can.beans': 'Can of Beans',
  'can.beans.empty': 'Empty Can Of Beans',
  'can.tuna': 'Can of Tuna',
  'can.tuna.empty': 'Empty Tuna Can',
  'candycane': 'Candy Cane',
  'candycaneclub': 'Candy Cane Club',
  'car.key': 'Car Key',
  'carburetor1': 'Low Quality Carburetor',
  'carburetor2': 'Medium Quality Carburetor',
  'carburetor3': 'High Quality Carburetor',
  'cctv.camera': 'CCTV Camera',
  'ceilinglight': 'Ceiling Light',
  'chainsaw': 'Chainsaw',
  'chair': 'Chair',
  'charcoal': 'Charcoal',
  'chicken.burned': 'Burnt Chicken',
  'chicken.cooked': 'Cooked Chicken',
  'chicken.raw': 'Raw Chicken Breast',
  'chicken.spoiled': 'Spoiled Chicken',
  'chineselantern': 'Chinese Lantern',
  'chocholate': 'Chocolate Bar',
  'clatter.helmet': 'Clatter Helmet',
  'clone.black.berry': 'Black Berry Clone',
  'clone.blue.berry': 'Blue Berry Clone',
  'clone.corn': 'Corn Clone',
  'clone.green.berry': 'Green Berry Clone',
  'clone.hemp': 'Hemp Clone',
  'clone.potato': 'Potato Clone',
  'clone.pumpkin': 'Pumpkin Plant Clone',
  'clone.red.berry': 'Red Berry Clone',
  'clone.white.berry': 'White Berry Clone',
  'clone.yellow.berry': 'Yellow Berry Clone',
  'cloth': 'Cloth',
  'coal': 'Coal',
  'coffee.can.helmet': 'Coffee Can Helmet',
  'coffin.storage': 'Coffin',
  'composter': 'Composter',
  'computerstation': 'Computer Station',
  'corn': 'Corn',
  'crankshaft1': 'Low Quality Crankshaft',
  'crankshaft2': 'Medium Quality Crankshaft',
  'crankshaft3': 'High Quality Crankshaft',
  'cratecostume': 'Crate Costume',
  'crossbow': 'Crossbow',
  'crude.oil': 'Crude Oil',
  'cupboard.tool': 'Tool Cupboard',
  'cursedcauldron': 'Cursed Cauldron',
  'deer.skull.mask': 'Bone Helmet',
  'deermeat.burned': 'Burnt Deer Meat',
  'deermeat.cooked': 'Cooked Deer Meat',
  'deermeat.raw': 'Raw Deer Meat',
  'diesel_barrel': 'Diesel Fuel',
  'diving.fins': 'Diving Fins',
  'diving.mask': 'Diving Mask',
  'diving.tank': 'Diving Tank',
  'diving.wetsuit': 'Wetsuit',
  'door.closer': 'Door Closer',
  'door.double.hinged.metal': 'Sheet Metal Double Door',
  'door.double.hinged.toptier': 'Armored Double Door',
  'door.double.hinged.wood': 'Wood Double Door',
  'door.hinged.industrial.a': 'Industrial Door',
  'door.hinged.metal': 'Sheet Metal Door',
  'door.hinged.toptier': 'Armored Door',
  'door.hinged.wood': 'Wooden Door',
  'door.key': 'Door Key',
  'dragondoorknocker': 'Dragon Door Knocker',
  'dropbox': 'Drop Box',
  'drumkit': 'Junkyard Drum Kit',
  'ducttape': 'Duct Tape',
  'easter.bronzeegg': 'Bronze Egg',
  'easter.goldegg': 'Gold Egg',
  'easter.paintedeggs': 'Painted Egg',
  'easter.silveregg': 'Silver Egg',
  'easterbasket': 'Egg Basket',
  'easterdoorwreath': 'Easter Door Wreath',
  'electric.andswitch': 'AND Switch',
  'electric.audioalarm': 'Audio Alarm',
  'electric.battery.rechargable.large': 'Large Rechargable Battery',
  'electric.battery.rechargable.medium': 'Medium Rechargable Battery',
  'electric.battery.rechargable.small': 'Small Rechargable Battery',
  'electric.blocker': 'Blocker',
  'electric.button': 'Button',
  'electric.cabletunnel': 'Cable Tunnel',
  'electric.counter': 'Counter',
  'electric.doorcontroller': 'Door Controller',
  'electric.flasherlight': 'Flasher Light',
  'electric.fuelgenerator.small': 'Small Generator',
  'electric.generator.small': 'Test Generator',
  'electric.hbhfsensor': 'HBHF Sensor',
  'electric.heater': 'Electric Heater',
  'electric.igniter': 'Igniter',
  'electric.laserdetector': 'Laser Detector',
  'electric.orswitch': 'OR Switch',
  'electric.pressurepad': 'Pressure Pad',
  'electric.random.switch': 'RAND Switch',
  'electric.rf.broadcaster': 'RF Broadcaster',
  'electric.rf.receiver': 'RF Receiver',
  'electric.simplelight': 'Simple Light',
  'electric.sirenlight': 'Siren Light',
  'electric.solarpanel.large': 'Large Solar Panel',
  'electric.splitter': 'Splitter',
  'electric.sprinkler': 'Sprinkler',
  'electric.switch': 'Switch',
  'electric.teslacoil': 'Tesla Coil',
  'electric.timer': 'Timer',
  'electric.xorswitch': 'XOR Switch',
  'electrical.branch': 'Electrical Branch',
  'electrical.combiner': 'Root Combiner',
  'electrical.memorycell': 'Memory Cell',
  'elevator': 'Elevator',
  'explosive.satchel': 'Satchel Charge',
  'explosive.timed': 'Timed Explosive Charge',
  'explosives': 'Explosives',
  'fat.animal': 'Animal Fat',
  'fertilizer': 'Fertilizer',
  'fireplace.stone': 'Stone Fireplace',
  'firework.boomer.blue': 'Blue Boomer',
  'firework.boomer.champagne': 'Champagne Boomer',
  'firework.boomer.green': 'Green Boomer',
  'firework.boomer.orange': 'Orange Boomer',
  'firework.boomer.red': 'Red Boomer',
  'firework.boomer.violet': 'Violet Boomer',
  'firework.romancandle.blue': 'Blue Roman Candle',
  'firework.romancandle.green': 'Green Roman Candle',
  'firework.romancandle.red': 'Red Roman Candle',
  'firework.romancandle.violet': 'Violet Roman Candle',
  'firework.volcano': 'White Volcano Firework',
  'firework.volcano.red': 'Red Volcano Firework',
  'firework.volcano.violet': 'Violet Volcano Firework',
  'fish.cooked': 'Cooked Fish',
  'fish.minnows': 'Minnows',
  'fish.raw': 'Raw Fish',
  'fish.troutsmall': 'Small Trout',
  'fishingrod.handmade': 'Handmade Fishing Rod',
  'fishtrap.small': 'Survival Fish Trap',
  'flamethrower': 'Flame Thrower',
  'flameturret': 'Flame Turret',
  'flare': 'Flare',
  'flashlight.held': 'Flashlight',
  'floor.grill': 'Floor grill',
  'floor.ladder.hatch': 'Ladder Hatch',
  'floor.triangle.grill': 'Floor triangle grill',
  'floor.triangle.ladder.hatch': 'Triangle Ladder Hatch',
  'fluid.combiner': 'Fluid Combiner',
  'fluid.splitter': 'Fluid Splitter',
  'fluid.switch': 'Fluid Switch & Pump',
  'fogmachine': 'Fogger-3000',
  'fridge': 'Fridge',
  'fun.bass': 'Shovel Bass',
  'fun.cowbell': 'Cowbell',
  'fun.flute': 'Pan Flute',
  'fun.guitar': 'Acoustic Guitar',
  'fun.jerrycanguitar': 'Jerry Can Guitar',
  'fun.tambourine': 'Canbourine',
  'fun.trumpet': 'Plumber\'s Trumpet',
  'fun.tuba': 'Sousaphone',
  'furnace': 'Furnace',
  'furnace.large': 'Large Furnace',
  'fuse': 'Electric Fuse',
  'gates.external.high.stone': 'High External Stone Gate',
  'gates.external.high.wood': 'High External Wooden Gate',
  'gears': 'Gears',
  'geiger.counter': 'Geiger Counter',
  'generator.wind.scrap': 'Wind Turbine',
  'ghostsheet': 'Ghost Costume',
  'giantcandycanedecor': 'Giant Candy Decor',
  'giantlollipops': 'Giant Lollipop Decor',
  'gloweyes': 'Glowing Eyes',
  'glue': 'Glue',
  'granolabar': 'Granola Bar',
  'gravestone': 'Gravestone',
  'green.berry': 'Green Berry',
  'grenade.beancan': 'Beancan Grenade',
  'grenade.f1': 'F1 Grenade',
  'grenade.smoke': 'Smoke Grenade',
  'gun.water': 'Water Gun',
  'gunpowder': 'Gun Powder',
  'guntrap': 'Shotgun Trap',
  'habrepair': 'Hab Repair',
  'halloween.candy': 'Halloween Candy',
  'halloween.lootbag.large': 'Large Loot Bag',
  'halloween.lootbag.medium': 'Medium Loot Bag',
  'halloween.lootbag.small': 'Small Loot Bag',
  'halloween.mummysuit': 'Mummy Suit',
  'halloween.surgeonsuit': 'Surgeon Scrubs',
  'hammer': 'Hammer',
  'hammer.salvaged': 'Salvaged Hammer',
  'hat.beenie': 'Beenie Hat',
  'hat.boonie': 'Boonie Hat',
  'hat.candle': 'Candle Hat',
  'hat.cap': 'Baseball Cap',
  'hat.dragonmask': 'Dragon Mask',
  'hat.miner': 'Miners Hat',
  'hat.ratmask': 'Rat Mask',
  'hat.wolf': 'Wolf Headdress',
  'hatchet': 'Hatchet',
  'hazmatsuit': 'Hazmat Suit',
  'hazmatsuit.spacesuit': 'Space Suit',
  'hazmatsuit_scientist': 'Scientist Suit',
  'hazmatsuit_scientist_peacekeeper': 'Scientist Suit',
  'healingtea': 'Basic Healing Tea',
  'healingtea.advanced': 'Advanced Healing Tea',
  'healingtea.pure': 'Pure Healing Tea',
  'heavy.plate.helmet': 'Heavy Plate Helmet',
  'heavy.plate.jacket': 'Heavy Plate Jacket',
  'heavy.plate.pants': 'Heavy Plate Pants',
  'hitchtroughcombo': 'Hitch & Trough',
  'hobobarrel': 'Hobo Barrel',
  'hoodie': 'Hoodie',
  'horse.armor.roadsign': 'Roadsign Horse Armor',
  'horse.armor.wood': 'Wooden Horse Armor',
  'horse.saddle': 'Horse Saddle',
  'horse.saddlebag': 'Saddle bag',
  'horse.shoes.advanced': 'High Quality Horse Shoes',
  'horse.shoes.basic': 'Basic Horse Shoes',
  'horsedung': 'Horse Dung',
  'horsemeat.burned': 'Burnt Horse Meat',
  'horsemeat.cooked': 'Cooked Horse Meat',
  'horsemeat.raw': 'Raw Horse Meat',
  'hosetool': 'Hose Tool',
  'hq.metal.ore': 'High Quality Metal Ore',
  'humanmeat.burned': 'Burnt Human Meat',
  'humanmeat.cooked': 'Cooked Human Meat',
  'humanmeat.raw': 'Raw Human Meat',
  'humanmeat.spoiled': 'Spoiled Human Meat',
  'icepick.salvaged': 'Salvaged Icepick',
  'innertube': 'Inner Tube',
  'innertube.horse': 'Inner Tube',
  'innertube.unicorn': 'Inner Tube',
  'jacket': 'Jacket',
  'jacket.snow': 'Snow Jacket',
  'jackhammer': 'Jackhammer',
  'jackolantern.angry': 'Jack O Lantern Angry',
  'jackolantern.happy': 'Jack O Lantern Happy',
  'jar.pickle': 'Pickles',
  'kayak': 'Kayak',
  'keycard_blue': 'Blue Keycard',
  'keycard_green': 'Green Keycard',
  'keycard_red': 'Red Keycard',
  'knife.bone': 'Bone Knife',
  'knife.butcher': 'Butcher Knife',
  'knife.combat': 'Combat Knife',
  'ladder.wooden.wall': 'Wooden Ladder',
  'lantern': 'Lantern',
  'largecandles': 'Large Candle Set',
  'largemedkit': 'Large Medkit',
  'leather': 'Leather',
  'lmg.m249': 'M249',
  'lock.code': 'Code Lock',
  'lock.key': 'Key Lock',
  'locker': 'Locker',
  'longsword': 'Longsword',
  'lowgradefuel': 'Low Grade Fuel',
  'lunar.firecrackers': 'Firecracker String',
  'mace': 'Mace',
  'machete': 'Machete',
  'mailbox': 'Mail Box',
  'map': 'Paper Map',
  'mask.balaclava': 'Improvised Balaclava',
  'mask.bandana': 'Bandana Mask',
  'maxhealthtea': 'Basic Max Health Tea',
  'maxhealthtea.advanced': 'Advanced Max Health Tea',
  'maxhealthtea.pure': 'Pure Max Health Tea',
  'meat.boar': 'Raw Pork',
  'meat.pork.burned': 'Burnt Pork',
  'meat.pork.cooked': 'Cooked Pork',
  'metal.facemask': 'Metal Facemask',
  'metal.fragments': 'Metal Fragments',
  'metal.ore': 'Metal Ore',
  'metal.plate.torso': 'Metal Chest Plate',
  'metal.refined': 'High Quality Metal',
  'metalblade': 'Metal Blade',
  'metalpipe': 'Metal Pipe',
  'metalspring': 'Metal Spring',
  'minihelicopter.repair': 'MC repair',
  'mining.pumpjack': 'Pump Jack',
  'mining.quarry': 'Mining Quarry',
  'mixingtable': 'Mixing Table',
  'modularcarlift': 'Modular Car Lift',
  'movembermoustache': 'Movember Moustache',
  'movembermoustachecard': 'Card Movember Moustache',
  'multiplegrenadelauncher': 'Multiple Grenade Launcher',
  'mushroom': 'Mushroom',
  'newyeargong': 'New Year Gong',
  'nightvisiongoggles': 'Night Vision Goggles',
  'note': 'Note',
  'oretea': 'Basic Ore Tea',
  'oretea.advanced': 'Advanced Ore Tea',
  'oretea.pure': 'Pure Ore Tea',
  'paddle': 'Paddle',
  'paddlingpool': 'Paddling Pool',
  'pants': 'Pants',
  'pants.shorts': 'Shorts',
  'paper': 'Paper',
  'partyhat': 'Party Hat',
  'photo': 'Photograph',
  'photoframe.landscape': 'Landscape Photo Frame',
  'photoframe.large': 'Large Photo Frame',
  'photoframe.portrait': 'Portrait Photo Frame',
  'piano': 'Wheelbarrow Piano',
  'pickaxe': 'Pickaxe',
  'pistol.eoka': 'Eoka Pistol',
  'pistol.m92': 'M92 Pistol',
  'pistol.nailgun': 'Nailgun',
  'pistol.python': 'Python Revolver',
  'pistol.revolver': 'Revolver',
  'pistol.semiauto': 'Semi-Automatic Pistol',
  'pistol.water': 'Water Pistol',
  'piston1': 'Low Quality Pistons',
  'piston2': 'Medium Quality Pistons',
  'piston3': 'High Quality Pistons',
  'pitchfork': 'Pitchfork',
  'planter.large': 'Large Planter Box',
  'planter.small': 'Small Planter Box',
  'plantfiber': 'Plant Fiber',
  'pookie.bear': 'Pookie Bear',
  'potato': 'Potato',
  'powered.water.purifier': 'Powered Water Purifier',
  'propanetank': 'Empty Propane Tank',
  'pumpkin': 'Pumpkin',
  'pumpkinbasket': 'Pumpkin Bucket',
  'radiationremovetea': 'Rad. Removal Tea',
  'radiationremovetea.advanced': 'Advanced Rad. Removal Tea',
  'radiationremovetea.pure': 'Pure Rad. Removal Tea',
  'radiationresisttea': 'Anti-Rad Tea',
  'radiationresisttea.advanced': 'Adv. Anti-Rad Tea',
  'radiationresisttea.pure': 'Pure Anti-Rad Tea',
  'red.berry': 'Red Berry',
  'research.table': 'Research Table',
  'researchpaper': 'Research Paper',
  'rf.detonator': 'RF Transmitter',
  'rf_pager': 'RF Pager',
  'rifle.ak': 'Assault Rifle',
  'rifle.bolt': 'Bolt Action Rifle',
  'rifle.l96': 'L96 Rifle',
  'rifle.lr300': 'LR-300 Assault Rifle',
  'rifle.m39': 'M39 Rifle',
  'rifle.semiauto': 'Semi-Automatic Rifle',
  'riflebody': 'Rifle Body',
  'riot.helmet': 'Riot Helmet',
  'roadsign.gloves': 'Roadsign Gloves',
  'roadsign.jacket': 'Road Sign Jacket',
  'roadsign.kilt': 'Road Sign Kilt',
  'roadsigns': 'Road Signs',
  'rock': 'Rock',
  'rocket.launcher': 'Rocket Launcher',
  'rope': 'Rope',
  'rug': 'Rug',
  'rug.bear': 'Rug Bear Skin',
  'rustige_egg_a': 'Rustigé Egg - Red',
  'rustige_egg_b': 'Rustigé Egg - Blue',
  'rustige_egg_c': 'Rustigé Egg - Purple',
  'rustige_egg_d': 'Rustigé Egg - Ivory',
  'salvaged.cleaver': 'Salvaged Cleaver',
  'salvaged.sword': 'Salvaged Sword',
  'samsite': 'SAM Site',
  'santabeard': 'Santa Beard',
  'santahat': 'Santa Hat',
  'scarecrow': 'Scarecrow',
  'scarecrow.suit': 'Scarecrow Suit',
  'scarecrowhead': 'Scarecrow Wrap',
  'scientistsuit_heavy': 'Heavy Scientist Suit',
  'scrap': 'Scrap',
  'scraptea': 'Basic Scrap Tea',
  'scraptea.advanced': 'Advanced Scrap Tea',
  'scraptea.pure': 'Pure Scrap Tea',
  'scraptransportheli.repair': 'ScrapTransportHeliRepair',
  'searchlight': 'Search Light',
  'secretlabchair': 'Secret Lab Chair',
  'seed.black.berry': 'Black Berry Seed',
  'seed.blue.berry': 'Blue Berry Seed',
  'seed.corn': 'Corn Seed',
  'seed.green.berry': 'Green Berry Seed',
  'seed.hemp': 'Hemp Seed',
  'seed.potato': 'Potato Seed',
  'seed.pumpkin': 'Pumpkin Seed',
  'seed.red.berry': 'Red Berry Seed',
  'seed.white.berry': 'White Berry Seed',
  'seed.yellow.berry': 'Yellow Berry Seed',
  'semibody': 'Semi Automatic Body',
  'sewingkit': 'Sewing Kit',
  'sheetmetal': 'Sheet Metal',
  'shelves': 'Salvaged Shelves',
  'shirt.collared': 'Shirt',
  'shirt.tanktop': 'Tank Top',
  'shoes.boots': 'Boots',
  'shotgun.double': 'Double Barrel Shotgun',
  'shotgun.pump': 'Pump Shotgun',
  'shotgun.spas12': 'Spas-12 Shotgun',
  'shotgun.waterpipe': 'Waterpipe Shotgun',
  'shutter.metal.embrasure.a': 'Metal horizontal embrasure',
  'shutter.metal.embrasure.b': 'Metal Vertical embrasure',
  'shutter.wood.a': 'Wood Shutters',
  'sickle': 'Sickle',
  'sign.hanging': 'Two Sided Hanging Sign',
  'sign.hanging.banner.large': 'Large Banner Hanging',
  'sign.hanging.ornate': 'Two Sided Ornate Hanging Sign',
  'sign.neon.125x125': 'Small Neon Sign',
  'sign.neon.125x215': 'Medium Neon Sign',
  'sign.neon.125x215.animated': 'Medium Animated Neon Sign',
  'sign.neon.xl': 'Large Neon Sign',
  'sign.neon.xl.animated': 'Large Animated Neon Sign',
  'sign.pictureframe.landscape': 'Landscape Picture Frame',
  'sign.pictureframe.portrait': 'Portrait Picture Frame',
  'sign.pictureframe.tall': 'Tall Picture Frame',
  'sign.pictureframe.xl': 'XL Picture Frame',
  'sign.pictureframe.xxl': 'XXL Picture Frame',
  'sign.pole.banner.large': 'Large Banner on pole',
  'sign.post.double': 'Double Sign Post',
  'sign.post.single': 'Single Sign Post',
  'sign.post.town': 'One Sided Town Sign Post',
  'sign.post.town.roof': 'Two Sided Town Sign Post',
  'sign.wooden.huge': 'Huge Wooden Sign',
  'sign.wooden.large': 'Large Wooden Sign',
  'sign.wooden.medium': 'Medium Wooden Sign',
  'sign.wooden.small': 'Small Wooden Sign',
  'skull.human': 'Human Skull',
  'skull.trophy': 'Skull Trophy',
  'skull.trophy.jar': 'Skull Trophy',
  'skull.trophy.jar2': 'Skull Trophy',
  'skull.trophy.table': 'Skull Trophy',
  'skull.wolf': 'Wolf Skull',
  'skull_fire_pit': 'Skull Fire Pit',
  'skulldoorknocker': 'Skull Door Knocker',
  'skullspikes': 'Skull Spikes',
  'skullspikes.candles': 'Skull Spikes',
  'skullspikes.pumpkin': 'Skull Spikes',
  'sled': 'Sled',
  'sled.xmas': 'Sled',
  'sleepingbag': 'Sleeping Bag',
  'small.oil.refinery': 'Small Oil Refinery',
  'smallcandles': 'Small Candle Set',
  'smallwaterbottle': 'Small Water Bottle',
  'smart.alarm': 'Smart Alarm',
  'smart.switch': 'Smart Switch',
  'smg.2': 'Custom SMG',
  'smg.mp5': 'MP5A4',
  'smg.thompson': 'Thompson',
  'smgbody': 'SMG Body',
  'snowball': 'Snowball',
  'snowballgun': 'Snowball Gun',
  'snowmachine': 'Snow Machine',
  'snowman': 'Snowman',
  'sofa': 'Sofa',
  'sparkplug1': 'Low Quality Spark Plugs',
  'sparkplug2': 'Medium Quality Spark Plugs',
  'sparkplug3': 'High Quality Spark Plugs',
  'spear.stone': 'Stone Spear',
  'spear.wooden': 'Wooden Spear',
  'spiderweb': 'Spider Webs',
  'spikes.floor': 'Wooden Floor Spikes',
  'spinner.wheel': 'Spinning wheel',
  'spookyspeaker': 'Spooky Speaker',
  'stash.small': 'Small Stash',
  'sticks': 'Sticks',
  'stocking.large': 'SUPER Stocking',
  'stocking.small': 'Small Stocking',
  'stone.pickaxe': 'Stone Pickaxe',
  'stonehatchet': 'Stone Hatchet',
  'stones': 'Stones',
  'storage.monitor': 'Storage Monitor',
  'strobelight': 'Strobe Light',
  'sulfur': 'Sulfur',
  'sulfur.ore': 'Sulfur Ore',
  'sunglasses': 'Sunglasses',
  'sunglasses02black': 'Sunglasses',
  'sunglasses02camo': 'Sunglasses',
  'sunglasses02red': 'Sunglasses',
  'sunglasses03black': 'Sunglasses',
  'sunglasses03chrome': 'Sunglasses',
  'sunglasses03gold': 'Sunglasses',
  'supply.signal': 'Supply Signal',
  'surveycharge': 'Survey Charge',
  'syringe.medical': 'Medical Syringe',
  'table': 'Table',
  'tactical.gloves': 'Tactical Gloves',
  'target.reactive': 'Reactive Target',
  'targeting.computer': 'Targeting Computer',
  'tarp': 'Tarp',
  'techparts': 'Tech Trash',
  'telephone': 'Telephone',
  'tool.binoculars': 'Binoculars',
  'tool.camera': 'Camera',
  'tool.instant_camera': 'Instant Camera',
  'toolgun': 'Garry\'s Mod Tool Gun',
  'torch': 'Torch',
  'trap.bear': 'Snap Trap',
  'trap.landmine': 'Land Mine',
  'tshirt': 'T-Shirt',
  'tshirt.long': 'Longsleeve T-Shirt',
  'tunalight': 'Tuna Can Lamp',
  'twitch.headset': 'Headset',
  'twitchsunglasses': 'Purple Sunglasses',
  'valve1': 'Low Quality Valves',
  'valve2': 'Medium Quality Valves',
  'valve3': 'High Quality Valves',
  'vehicle.1mod.cockpit': 'Cockpit Vehicle Module',
  'vehicle.1mod.cockpit.armored': 'Armored Cockpit Vehicle Module',
  'vehicle.1mod.cockpit.with.engine': 'Cockpit With Engine Vehicle Module',
  'vehicle.1mod.engine': 'Engine Vehicle Module',
  'vehicle.1mod.flatbed': 'Flatbed Vehicle Module',
  'vehicle.1mod.passengers.armored': 'Armored Passenger Vehicle Module',
  'vehicle.1mod.rear.seats': 'Rear Seats Vehicle Module',
  'vehicle.1mod.storage': 'Storage Vehicle Module',
  'vehicle.1mod.taxi': 'Taxi Vehicle Module',
  'vehicle.2mod.flatbed': 'Large Flatbed Vehicle Module',
  'vehicle.2mod.fuel.tank': 'Fuel Tank Vehicle Module',
  'vehicle.2mod.passengers': 'Passenger Vehicle Module',
  'vehicle.chassis': 'Generic vehicle chassis',
  'vehicle.chassis.2mod': 'Small Chassis',
  'vehicle.chassis.3mod': 'Medium Chassis',
  'vehicle.chassis.4mod': 'Large Chassis',
  'vehicle.module': 'Generic vehicle module',
  'vending.machine': 'Vending Machine',
  'wall.external.high': 'High External Wooden Wall',
  'wall.external.high.ice': 'High Ice Wall',
  'wall.external.high.stone': 'High External Stone Wall',
  'wall.frame.cell': 'Prison Cell Wall',
  'wall.frame.cell.gate': 'Prison Cell Gate',
  'wall.frame.fence': 'Chainlink Fence',
  'wall.frame.fence.gate': 'Chainlink Fence Gate',
  'wall.frame.garagedoor': 'Garage Door',
  'wall.frame.netting': 'Netting',
  'wall.frame.shopfront': 'Shop Front',
  'wall.frame.shopfront.metal': 'Metal Shop Front',
  'wall.graveyard.fence': 'Graveyard Fence',
  'wall.ice.wall': 'Short Ice Wall',
  'wall.window.bars.metal': 'Metal Window Bars',
  'wall.window.bars.toptier': 'Reinforced Glass Window',
  'wall.window.bars.wood': 'Wooden Window Bars',
  'wall.window.glass.reinforced': 'Strengthened Glass Window',
  'watchtower.wood': 'Watch Tower',
  'water': 'Water',
  'water.barrel': 'Water Barrel',
  'water.catcher.large': 'Large Water Catcher',
  'water.catcher.small': 'Small Water Catcher',
  'water.purifier': 'Water Purifier',
  'water.salt': 'Salt Water',
  'waterjug': 'Water Jug',
  'waterpump': 'Water Pump',
  'weapon.mod.8x.scope': '16x Zoom Scope',
  'weapon.mod.flashlight': 'Weapon flashlight',
  'weapon.mod.holosight': 'Holosight',
  'weapon.mod.lasersight': 'Weapon Lasersight',
  'weapon.mod.muzzleboost': 'Muzzle Boost',
  'weapon.mod.muzzlebrake': 'Muzzle Brake',
  'weapon.mod.silencer': 'Silencer',
  'weapon.mod.simplesight': 'Simple Handmade Sight',
  'weapon.mod.small.scope': '8x Zoom Scope',
  'white.berry': 'White Berry',
  'wiretool': 'Wire Tool',
  'wolfmeat.burned': 'Burnt Wolf Meat',
  'wolfmeat.cooked': 'Cooked Wolf Meat',
  'wolfmeat.raw': 'Raw Wolf Meat',
  'wolfmeat.spoiled': 'Spoiled Wolf Meat',
  'wood': 'Wood',
  'wood.armor.helmet': 'Wood Armor Helmet',
  'wood.armor.jacket': 'Wood Chestplate',
  'wood.armor.pants': 'Wood Armor Pants',
  'woodcross': 'Wooden Cross',
  'woodtea': 'Basic Wood Tea',
  'woodtea.advanced': 'Advanced Wood Tea',
  'woodtea.pure': 'Pure Wood Tea',
  'workbench1': 'Work Bench Level 1',
  'workbench2': 'Work Bench Level 2',
  'workbench3': 'Work Bench Level 3',
  'wrappedgift': 'Wrapped Gift',
  'wrappingpaper': 'Wrapping Paper',
  'xmas.decoration.baubels': 'Decorative Baubels',
  'xmas.decoration.candycanes': 'Decorative Plastic Candy Canes',
  'xmas.decoration.gingerbreadmen': 'Decorative Gingerbread Men',
  'xmas.decoration.lights': 'Tree Lights',
  'xmas.decoration.pinecone': 'Decorative Pinecones',
  'xmas.decoration.star': 'Star Tree Topper',
  'xmas.decoration.tinsel': 'Decorative Tinsel',
  'xmas.door.garland': 'Festive Doorway Garland',
  'xmas.lightstring': 'Christmas Lights',
  'xmas.lightstring.advanced': 'Deluxe Christmas Lights',
  'xmas.present.large': 'Large Present',
  'xmas.present.medium': 'Medium Present',
  'xmas.present.small': 'Small Present',
  'xmas.tree': 'Christmas Tree',
  'xmas.window.garland': 'Festive Window Garland',
  'xmasdoorwreath': 'Christmas Door Wreath',
  'xylophone': 'Xylobone',
  'yellow.berry': 'Yellow Berry'
};

// Icon Manager optimizado con rustedit.io
class IconManager {
  private cache = new Map<string, string>();
  private sources = [
    {
      name: 'rustedit',
      baseUrl: 'https://www.rustedit.io/images/imagelibrary',
      format: (name: string) => `${name}.png` // Mantiene puntos - compatible con ImageLibrary uMod
    },
    {
      name: 'rustlabs-fallback',
      baseUrl: 'https://rustlabs.com/img/items180',
      format: (name: string) => `${name.replace(/\./g, '')}.png` // Remueve puntos para rustlabs
    }
  ];

  private defaultIcon = 'https://www.rustedit.io/images/imagelibrary/stone.png';

  // Obtener URL del icono (usa cache automático)
  getItemIconSync(itemShortname: string): string {
    if (this.cache.has(itemShortname)) {
      return this.cache.get(itemShortname)!;
    }

    // Usar rustedit.io como fuente principal (ya probada y funcional)
    const url = `${this.sources[0].baseUrl}/${this.sources[0].format(itemShortname)}`;
    this.cache.set(itemShortname, url);
    return url;
  }

  // Obtener URL con fallback (para casos donde necesites más robustez)
  getItemIconWithFallback(itemShortname: string): string {
    // Si ya está en cache, usarlo
    if (this.cache.has(itemShortname)) {
      return this.cache.get(itemShortname)!;
    }

    // Primera opción: rustedit.io (ya sabemos que funciona)
    const primaryUrl = `${this.sources[0].baseUrl}/${this.sources[0].format(itemShortname)}`;
    this.cache.set(itemShortname, primaryUrl);
    return primaryUrl;
  }

  // Precargar iconos comunes para mejor rendimiento
  preloadCommonIcons(): void {
    const commonItems = [
      'wood', 'stone', 'metal.fragments', 'cloth', 'leather',
      'scrap', 'lowgradefuel', 'sulfur', 'metal.ore', 'hq.metal.ore',
      'rifle.ak', 'pistol.python', 'shotgun.pump', 'crossbow'
    ];

    commonItems.forEach(item => this.getItemIconSync(item));
  }

  // Limpiar cache
  clearCache(): void {
    this.cache.clear();
  }

  // Obtener estadísticas del cache
  getCacheStats(): { size: number; items: string[] } {
    return {
      size: this.cache.size,
      items: Array.from(this.cache.keys())
    };
  }
}

// Instancia global
const iconManager = new IconManager();

// Función principal - LA QUE DEBES USAR EN TUS COMPONENTES
export const getItemIconUrl = (itemShortname: string): string => {
  return iconManager.getItemIconSync(itemShortname);
};

// Función con fallback (opcional - para casos especiales)
export const getItemIconUrlWithFallback = (itemShortname: string): string => {
  return iconManager.getItemIconWithFallback(itemShortname);
};

// Función para precargar iconos comunes (opcional - para mejor rendimiento)
export const preloadCommonIcons = (): void => {
  iconManager.preloadCommonIcons();
};

// Función para limpiar cache (opcional - para desarrollo/debug)
export const clearIconCache = (): void => {
  iconManager.clearCache();
};

// Función para obtener stats del cache (opcional - para debug)
export const getIconCacheStats = () => {
  return iconManager.getCacheStats();
};

// Helper function to get item display name (sin cambios)
export const getItemDisplayName = (itemShortname: string): string => {
  return ITEM_DISPLAY_NAMES[itemShortname] || itemShortname
    .split('.')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
};
